export { default as NavBar } from './NavBar/NavBar';
export { default as Hero } from './Hero/Hero';
export { default as Features } from './Features/Features';
export { default as Cta } from "./Cta/Cta";
export { default as Testimonials } from "./Testimonials/Testimonials";
export { default as Contact } from "./Contact/Contact";
export { default as About } from "./About/About";
export { default as Footer } from "./Footer/Footer";
export { default as ResourceDetails } from "./ResourceDetails/ResourceDetails";